apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory
    spec:
      containers:
      - name: inventory
        image: ddd-inventory:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        # Reserved for future use.
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75.0 -Dspring.profiles.active=dev"
        - name: DATABASE_HOST
          value: "postgresql.postgresql"
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_USERNAME
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "postgres"
        - name: DATABASE_SCHEMA
          value: "inventory"
        - name: RABBITMQ_HOST
          value: "rabbitmq.rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: "user"
        - name: RABBITMQ_PASSWORD
          value: "rabbitmq"
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"


