apiVersion: v1
kind: Service
metadata:
  name: ddd-foundation-service
  namespace: application
spec:
  selector:
    app.kubernetes.io/name: ddd-foundation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
