apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: inventory
spec:
  selector:
    app.kubernetes.io/name: inventory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
