/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.myshop.shareddomain.event.order;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Orderer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8447238596046044057L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Orderer\",\"namespace\":\"com.myshop.shareddomain.event.order\",\"fields\":[{\"name\":\"memberId\",\"type\":{\"type\":\"record\",\"name\":\"MemberId\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Orderer> ENCODER =
      new BinaryMessageEncoder<Orderer>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Orderer> DECODER =
      new BinaryMessageDecoder<Orderer>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Orderer> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Orderer> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Orderer> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Orderer>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Orderer to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Orderer from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Orderer instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Orderer fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.myshop.shareddomain.event.order.MemberId memberId;
  private java.lang.String name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Orderer() {}

  /**
   * All-args constructor.
   * @param memberId The new value for memberId
   * @param name The new value for name
   */
  public Orderer(com.myshop.shareddomain.event.order.MemberId memberId, java.lang.String name) {
    this.memberId = memberId;
    this.name = name;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return memberId;
    case 1: return name;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: memberId = (com.myshop.shareddomain.event.order.MemberId)value$; break;
    case 1: name = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'memberId' field.
   * @return The value of the 'memberId' field.
   */
  public com.myshop.shareddomain.event.order.MemberId getMemberId() {
    return memberId;
  }


  /**
   * Sets the value of the 'memberId' field.
   * @param value the value to set.
   */
  public void setMemberId(com.myshop.shareddomain.event.order.MemberId value) {
    this.memberId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Creates a new Orderer RecordBuilder.
   * @return A new Orderer RecordBuilder
   */
  public static com.myshop.shareddomain.event.order.Orderer.Builder newBuilder() {
    return new com.myshop.shareddomain.event.order.Orderer.Builder();
  }

  /**
   * Creates a new Orderer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Orderer RecordBuilder
   */
  public static com.myshop.shareddomain.event.order.Orderer.Builder newBuilder(com.myshop.shareddomain.event.order.Orderer.Builder other) {
    if (other == null) {
      return new com.myshop.shareddomain.event.order.Orderer.Builder();
    } else {
      return new com.myshop.shareddomain.event.order.Orderer.Builder(other);
    }
  }

  /**
   * Creates a new Orderer RecordBuilder by copying an existing Orderer instance.
   * @param other The existing instance to copy.
   * @return A new Orderer RecordBuilder
   */
  public static com.myshop.shareddomain.event.order.Orderer.Builder newBuilder(com.myshop.shareddomain.event.order.Orderer other) {
    if (other == null) {
      return new com.myshop.shareddomain.event.order.Orderer.Builder();
    } else {
      return new com.myshop.shareddomain.event.order.Orderer.Builder(other);
    }
  }

  /**
   * RecordBuilder for Orderer instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Orderer>
    implements org.apache.avro.data.RecordBuilder<Orderer> {

    private com.myshop.shareddomain.event.order.MemberId memberId;
    private com.myshop.shareddomain.event.order.MemberId.Builder memberIdBuilder;
    private java.lang.String name;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.myshop.shareddomain.event.order.Orderer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.memberId)) {
        this.memberId = data().deepCopy(fields()[0].schema(), other.memberId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasMemberIdBuilder()) {
        this.memberIdBuilder = com.myshop.shareddomain.event.order.MemberId.newBuilder(other.getMemberIdBuilder());
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Orderer instance
     * @param other The existing instance to copy.
     */
    private Builder(com.myshop.shareddomain.event.order.Orderer other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.memberId)) {
        this.memberId = data().deepCopy(fields()[0].schema(), other.memberId);
        fieldSetFlags()[0] = true;
      }
      this.memberIdBuilder = null;
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'memberId' field.
      * @return The value.
      */
    public com.myshop.shareddomain.event.order.MemberId getMemberId() {
      return memberId;
    }


    /**
      * Sets the value of the 'memberId' field.
      * @param value The value of 'memberId'.
      * @return This builder.
      */
    public com.myshop.shareddomain.event.order.Orderer.Builder setMemberId(com.myshop.shareddomain.event.order.MemberId value) {
      validate(fields()[0], value);
      this.memberIdBuilder = null;
      this.memberId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'memberId' field has been set.
      * @return True if the 'memberId' field has been set, false otherwise.
      */
    public boolean hasMemberId() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'memberId' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.myshop.shareddomain.event.order.MemberId.Builder getMemberIdBuilder() {
      if (memberIdBuilder == null) {
        if (hasMemberId()) {
          setMemberIdBuilder(com.myshop.shareddomain.event.order.MemberId.newBuilder(memberId));
        } else {
          setMemberIdBuilder(com.myshop.shareddomain.event.order.MemberId.newBuilder());
        }
      }
      return memberIdBuilder;
    }

    /**
     * Sets the Builder instance for the 'memberId' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.myshop.shareddomain.event.order.Orderer.Builder setMemberIdBuilder(com.myshop.shareddomain.event.order.MemberId.Builder value) {
      clearMemberId();
      memberIdBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'memberId' field has an active Builder instance
     * @return True if the 'memberId' field has an active Builder instance
     */
    public boolean hasMemberIdBuilder() {
      return memberIdBuilder != null;
    }

    /**
      * Clears the value of the 'memberId' field.
      * @return This builder.
      */
    public com.myshop.shareddomain.event.order.Orderer.Builder clearMemberId() {
      memberId = null;
      memberIdBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.myshop.shareddomain.event.order.Orderer.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.myshop.shareddomain.event.order.Orderer.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Orderer build() {
      try {
        Orderer record = new Orderer();
        if (memberIdBuilder != null) {
          try {
            record.memberId = this.memberIdBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("memberId"));
            throw e;
          }
        } else {
          record.memberId = fieldSetFlags()[0] ? this.memberId : (com.myshop.shareddomain.event.order.MemberId) defaultValue(fields()[0]);
        }
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Orderer>
    WRITER$ = (org.apache.avro.io.DatumWriter<Orderer>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Orderer>
    READER$ = (org.apache.avro.io.DatumReader<Orderer>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.memberId.customEncode(out);

    out.writeString(this.name);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.memberId == null) {
        this.memberId = new com.myshop.shareddomain.event.order.MemberId();
      }
      this.memberId.customDecode(in);

      this.name = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.memberId == null) {
            this.memberId = new com.myshop.shareddomain.event.order.MemberId();
          }
          this.memberId.customDecode(in);
          break;

        case 1:
          this.name = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










