spring:
  profiles:
    active: local
---
spring:
  profiles:
    group:
      local: common
---
spring:
  profiles:
    group:
      dev: common
---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: ddd-inventory
  jpa:
#    database: postgresql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  flyway:
    enabled: true
    validate-migration-naming: true
    locations: classpath:db/migration/common, classpath:db/migration/sample
    baseline-on-migrate: true
  sql:
    init:
      mode: never
server:
  address: 0.0.0.0
  port: ${PORT:8080}
  internal-port: 8200
  servlet:
    context-path: /
  tomcat:
    accept-count: 100
    threads:
      max: 200
      min-spare: 100
logging:
  level:
    root: INFO
---
spring:
  config:
    activate:
      on-profile: local
  flyway:
    url: jdbc:postgresql://localhost:5432/inventory
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 50
