# 2 Nodes (1 control plane + 1 worker nodes)
# Worker node exposes ports 80, 443, and 15672 (RabbitMQ management console)
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 15672
        hostPort: 15672
        protocol: TCP
